workflows:
  my-workflow:
    name: Tiwee


  
      
    
    
    
    version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  
   dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.4
  flutter_riverpod: ^1.0.3
  lottie: ^1.2.1
  google_fonts: ^2.2.0
  line_icons: ^2.0.1
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  unicons: ^2.0.2
  font_awesome_flutter: ^9.2.0
  carousel_slider: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  better_player: ^0.0.81
  flutter_staggered_grid_view: ^0.6.1
  url_launcher: ^6.0.18
   
      dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Tiwee.png"

  flutter_test:
    sdk: flutter
    
     flutter_lints: ^1.0.0
     
     
     flutter:
      uses-material-design: true
assets:
     - assets/animation/
     - assets/icons/
     
     
    
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    
        
      scripts:
        - echo 'Post-publish script'
